# Generated by Django 4.2 on 2023-06-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcategory',
            name='category',
            field=models.CharField(choices=[('TK', 'Tank'), ('HL', 'Heal'), ('DD', 'Damage Dealer'), ('TD', 'Treader'), ('GM', 'GuuldMaster'), ('QG', 'Quest Giver'), ('SM', 'Smith'), ('TN', 'Tanner'), ('PM', 'Poison Master'), ('SM', 'Spell Master')], max_length=100, null=True),
        ),
    ]
