# Generated by Django 4.2 on 2023-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachment_type',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
