# Generated by Django 4.2 on 2023-06-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
