# Generated by Django 4.2 on 2023-06-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_alter_announcement_attachment_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementresponse',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
