# Generated by Django 4.2 on 2023-06-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_announcementresponse_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementresponse',
            name='is_taken',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
