# Generated by Django 4.2 on 2023-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_remove_announcementresponse_is_taken_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementresponse',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
